apiVersion: v1
kind: ConfigMap
metadata:
  name: fiap-mecanica-config
  namespace: fiap-mecanica
  labels:
    app: fiap-mecanica
data:
  NODE_ENV: "production"
  PORT: "3000"
  API_PREFIX: "api/v1"
  JWT_EXPIRATION: "24h"
  POSTGRES_DB: "workshop_db"
  POSTGRES_USER: "workshop"
