apiVersion: apps/v1
kind: Deployment
metadata:
  name: fiap-mecanica-api
  namespace: fiap-mecanica
  labels:
    app: fiap-mecanica-api
spec:
  replicas: 2
  selector:
    matchLabels:
      app: fiap-mecanica-api
  template:
    metadata:
      labels:
        app: fiap-mecanica-api
    spec:
      containers:
        - name: api
          image: fiap-mecanica-api:latest
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 3000
          envFrom:
            - configMapRef:
                name: fiap-mecanica-config
            - secretRef:
                name: fiap-mecanica-secrets
          env:
            - name: DD_SERVICE
              value: "fiap-mecanica-api"
            - name: DD_ENV
              value: "production"
            - name: DD_VERSION
              value: "1.0.0"
            - name: DD_AGENT_HOST
              valueFrom:
                fieldRef:
                  fieldPath: status.hostIP
            - name: DD_AGENT_PORT
              value: "8126"
            - name: DD_TRACE_SAMPLE_RATE
              value: "1"
            - name: DD_LOGS_INJECTION
              value: "true"
          resources:
            requests:
              memory: "256Mi"
              cpu: "250m"
            limits:
              memory: "512Mi"
              cpu: "500m"
          livenessProbe:
            httpGet:
              path: /api/v1/health
              port: 3000
            initialDelaySeconds: 30
            periodSeconds: 10
            failureThreshold: 3
          readinessProbe:
            httpGet:
              path: /api/v1/health
              port: 3000
            initialDelaySeconds: 10
            periodSeconds: 5
            failureThreshold: 3
      initContainers:
        - name: db-migrate
          image: fiap-mecanica-api:latest
          imagePullPolicy: IfNotPresent
          command: ["npx", "prisma", "migrate", "deploy"]
          envFrom:
            - secretRef:
                name: fiap-mecanica-secrets
