apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: fiap-mecanica-secrets
  namespace: fiap-mecanica
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: aws-secrets-manager
    kind: ClusterSecretStore
  target:
    name: fiap-mecanica-secrets
    creationPolicy: Owner
  data:
    - secretKey: DATABASE_URL
      remoteRef:
        key: fiap-mecanica/hmg/database-url
    - secretKey: JWT_SECRET
      remoteRef:
        key: fiap-mecanica/hmg/jwt-secret
